services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8000"
    command: ["python3", "-m", "flask", "run", "--host=0.0.0.0", "--port=8000"]
    
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - app
    command: ["/usr/local/bin/start_and_test.sh"]