version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/chess_engine:delegated
    develop:
      watch:
        - action: sync
          path: .