services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - DATABASE_URL
      - CHESS_DB_SECRET_KEY
      - APP_URL=http://localhost:8000
    command: ["gunicorn", "--chdir", "/chess_engine", "-w", "1", "-b", "0.0.0.0:8000", "app:app", "--log-level", "debug", "--access-logfile", "-", "--error-logfile", "-"]

  test:
    volumes:
      - ./chess_engine/static/screenshots:/static/screenshots
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - app
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - DATABASE_URL
      - CHESS_DB_SECRET_KEY
      - APP_URL=http://localhost:8000
    command: ["/usr/local/bin/start_and_test.sh"]

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db

volumes:
  postgres_data: