# syntax=docker/dockerfile:1
ARG PYTHON_VERSION=3.12
FROM python:${PYTHON_VERSION}-slim AS base

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

WORKDIR /chess_engine

# Install required packages for Chrome and ChromeDriver + dos2unix (to read script)
RUN apt-get update \
    && apt-get install -y \
       wget \
       unzip \
       curl \
       gnupg \
       dos2unix

# Install Chrome
RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list \
    && apt-get update \
    && apt-get install -y google-chrome-stable

# Set chrome driver version
ENV CHROME_DRIVER_VERSION=114.0.5735.90

# Install ChromeDriver
RUN wget -q --continue -P /tmp/ https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip \
    && unzip /tmp/chromedriver_linux64.zip -d /usr/local/bin/ \
    && rm /tmp/chromedriver_linux64.zip

# Install required Python packages
RUN pip install --upgrade pip \
    && pip install pytest selenium webdriver-manager

RUN apt-get update && apt-get install -y libpq-dev build-essential

COPY requirements.txt ./
RUN --mount=type=cache,target=/root/.cache/pip \
    --mount=type=bind,source=requirements.txt,target=requirements.txt \
    python -m pip install --no-cache-dir -r requirements.txt

COPY start_and_test.sh /usr/local/bin/start_and_test.sh
RUN dos2unix /usr/local/bin/start_and_test.sh
RUN chmod +x /usr/local/bin/start_and_test.sh

COPY . .