name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:26.1.1
        options: --privileged

    env:
      APP_URL: http://localhost:5000
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-v1-${{ hashFiles('Dockerfile', 'requirements.txt', 'docker-compose.yml', 'Dockerfile.test') }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Build and run Docker test container
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          CHESS_DB_SECRET_KEY: ${{ secrets.CHESS_DB_SECRET_KEY }}
          PYTHONPATH: /chess_engine/src/chess_app
        run: |
          set -e
          mkdir -p chess_engine/src/chess_app/static/screenshots
          docker compose up --build -d db
          docker compose up --build -d app
          sleep 10
          docker compose exec -T app python /chess_engine/src/chess_app/init_db.py
          sleep 10
          docker compose up --build --abort-on-container-exit test
          docker cp chess_engine-test-1:src/chess_app/static/screenshots chess_engine/src/chess_app/static/screenshots
          ls -l chess_engine/src/chess_app/static/screenshots
          exit_code=$?
          docker compose down
          exit $exit_code

      - name: Verify Screenshot Directory
        if: always()
        run: ls -l chess_engine/src/chess_app/static/screenshots

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: screenshot
          path: chess_engine/src/chess_app/static/screenshots

      - name: Shut down Docker containers
        if: always()
        run: |
          docker-compose down